// Hand-maintained Go stubs for asr/proto/asr.proto.
//
// In a normal workflow these would be generated by `make asr-proto-go`
// (which invokes protoc-gen-go + protoc-gen-go-grpc). They're checked in
// here so the Go module compiles without requiring the protoc toolchain
// during day-to-day development. If you change asr/proto/asr.proto:
//
//   1. Install protoc + plugins (see asr/README.md).
//   2. Run `make asr-proto-go` from the repo root.
//   3. Replace this file with the generated output.
//
// This stub uses the standard google.golang.org/protobuf reflection API and
// the generated-code shape `protoc-gen-go` would emit, just without the
// protoreflect descriptor table (we don't need reflection in the gRPC
// client path; the on-the-wire encoding is driven by the field tags).

package pb

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"

	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

// Verify that this generated code is sufficiently up-to-date.
const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Suppress imports the wire format does not directly exercise but the
// service handlers below reference.
var (
	_ = emptypb.Empty{}
)

// ─── StartSessionRequest ─────────────────────────────────────────────────────

type StartSessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId                   string            `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CallId                   string            `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	ModelId                  string            `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Language                 string            `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	RequestedTokenTtlSeconds uint32            `protobuf:"varint,5,opt,name=requested_token_ttl_seconds,json=requestedTokenTtlSeconds,proto3" json:"requested_token_ttl_seconds,omitempty"`
	Metadata                 map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *StartSessionRequest) Reset()         { *x = StartSessionRequest{} }
func (x *StartSessionRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*StartSessionRequest) ProtoMessage()    {}
func (x *StartSessionRequest) ProtoReflect() protoreflect.Message {
	return messageState(&x.state, x, asrMessageInfos[0])
}

func (x *StartSessionRequest) GetUserId() string                   { if x != nil { return x.UserId };                   return "" }
func (x *StartSessionRequest) GetCallId() string                   { if x != nil { return x.CallId };                   return "" }
func (x *StartSessionRequest) GetModelId() string                  { if x != nil { return x.ModelId };                  return "" }
func (x *StartSessionRequest) GetLanguage() string                 { if x != nil { return x.Language };                 return "" }
func (x *StartSessionRequest) GetRequestedTokenTtlSeconds() uint32 { if x != nil { return x.RequestedTokenTtlSeconds }; return 0 }
func (x *StartSessionRequest) GetMetadata() map[string]string      { if x != nil { return x.Metadata };                 return nil }

// ─── StartSessionResponse ────────────────────────────────────────────────────

type StartSessionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId   string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ModelId     string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	SampleRate  int32                  `protobuf:"varint,3,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	FrameFormat string                 `protobuf:"bytes,4,opt,name=frame_format,json=frameFormat,proto3" json:"frame_format,omitempty"`
	ExpiresAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
}

func (x *StartSessionResponse) Reset()         { *x = StartSessionResponse{} }
func (x *StartSessionResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*StartSessionResponse) ProtoMessage()    {}
func (x *StartSessionResponse) ProtoReflect() protoreflect.Message {
	return messageState(&x.state, x, asrMessageInfos[1])
}

func (x *StartSessionResponse) GetSessionId() string                 { if x != nil { return x.SessionId };   return "" }
func (x *StartSessionResponse) GetModelId() string                   { if x != nil { return x.ModelId };     return "" }
func (x *StartSessionResponse) GetSampleRate() int32                 { if x != nil { return x.SampleRate };  return 0 }
func (x *StartSessionResponse) GetFrameFormat() string               { if x != nil { return x.FrameFormat }; return "" }
func (x *StartSessionResponse) GetExpiresAt() *timestamppb.Timestamp { if x != nil { return x.ExpiresAt };   return nil }

// ─── EndSession ──────────────────────────────────────────────────────────────

type EndSessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *EndSessionRequest) Reset()         { *x = EndSessionRequest{} }
func (x *EndSessionRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*EndSessionRequest) ProtoMessage()    {}
func (x *EndSessionRequest) ProtoReflect() protoreflect.Message {
	return messageState(&x.state, x, asrMessageInfos[2])
}
func (x *EndSessionRequest) GetSessionId() string { if x != nil { return x.SessionId }; return "" }

type EndSessionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FinalTranscript string `protobuf:"bytes,1,opt,name=final_transcript,json=finalTranscript,proto3" json:"final_transcript,omitempty"`
	FinalCount      uint32 `protobuf:"varint,2,opt,name=final_count,json=finalCount,proto3" json:"final_count,omitempty"`
}

func (x *EndSessionResponse) Reset()         { *x = EndSessionResponse{} }
func (x *EndSessionResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*EndSessionResponse) ProtoMessage()    {}
func (x *EndSessionResponse) ProtoReflect() protoreflect.Message {
	return messageState(&x.state, x, asrMessageInfos[3])
}
func (x *EndSessionResponse) GetFinalTranscript() string { if x != nil { return x.FinalTranscript }; return "" }
func (x *EndSessionResponse) GetFinalCount() uint32      { if x != nil { return x.FinalCount };      return 0 }

// ─── GetSession / SessionInfo ────────────────────────────────────────────────

type GetSessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *GetSessionRequest) Reset()         { *x = GetSessionRequest{} }
func (x *GetSessionRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*GetSessionRequest) ProtoMessage()    {}
func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	return messageState(&x.state, x, asrMessageInfos[4])
}
func (x *GetSessionRequest) GetSessionId() string { if x != nil { return x.SessionId }; return "" }

type SessionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State                 string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	StartedAt             *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	LastActivityAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_activity_at,json=lastActivityAt,proto3" json:"last_activity_at,omitempty"`
	AudioSecondsProcessed uint32                 `protobuf:"varint,4,opt,name=audio_seconds_processed,json=audioSecondsProcessed,proto3" json:"audio_seconds_processed,omitempty"`
	PartialCount          uint32                 `protobuf:"varint,5,opt,name=partial_count,json=partialCount,proto3" json:"partial_count,omitempty"`
	FinalCount            uint32                 `protobuf:"varint,6,opt,name=final_count,json=finalCount,proto3" json:"final_count,omitempty"`
}

func (x *SessionInfo) Reset()         { *x = SessionInfo{} }
func (x *SessionInfo) String() string { return protoimpl.X.MessageStringOf(x) }
func (*SessionInfo) ProtoMessage()    {}
func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	return messageState(&x.state, x, asrMessageInfos[5])
}
func (x *SessionInfo) GetState() string                            { if x != nil { return x.State };                 return "" }
func (x *SessionInfo) GetStartedAt() *timestamppb.Timestamp        { if x != nil { return x.StartedAt };             return nil }
func (x *SessionInfo) GetLastActivityAt() *timestamppb.Timestamp   { if x != nil { return x.LastActivityAt };        return nil }
func (x *SessionInfo) GetAudioSecondsProcessed() uint32            { if x != nil { return x.AudioSecondsProcessed }; return 0 }
func (x *SessionInfo) GetPartialCount() uint32                     { if x != nil { return x.PartialCount };          return 0 }
func (x *SessionInfo) GetFinalCount() uint32                       { if x != nil { return x.FinalCount };            return 0 }

// ─── HealthResponse ──────────────────────────────────────────────────────────

type HealthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status           string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version          string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds    uint64   `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	LoadedModels     []string `protobuf:"bytes,4,rep,name=loaded_models,json=loadedModels,proto3" json:"loaded_models,omitempty"`
	ActiveSessions   uint32   `protobuf:"varint,5,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	WorkerPoolSize   uint32   `protobuf:"varint,6,opt,name=worker_pool_size,json=workerPoolSize,proto3" json:"worker_pool_size,omitempty"`
	WorkerPoolInUse  uint32   `protobuf:"varint,7,opt,name=worker_pool_in_use,json=workerPoolInUse,proto3" json:"worker_pool_in_use,omitempty"`
	EngineMode       string   `protobuf:"bytes,8,opt,name=engine_mode,json=engineMode,proto3" json:"engine_mode,omitempty"`
	EngineTarget     string   `protobuf:"bytes,9,opt,name=engine_target,json=engineTarget,proto3" json:"engine_target,omitempty"`
}

func (x *HealthResponse) Reset()         { *x = HealthResponse{} }
func (x *HealthResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*HealthResponse) ProtoMessage()    {}
func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	return messageState(&x.state, x, asrMessageInfos[6])
}
func (x *HealthResponse) GetStatus() string             { if x != nil { return x.Status };          return "" }
func (x *HealthResponse) GetVersion() string            { if x != nil { return x.Version };         return "" }
func (x *HealthResponse) GetUptimeSeconds() uint64      { if x != nil { return x.UptimeSeconds };   return 0 }
func (x *HealthResponse) GetLoadedModels() []string     { if x != nil { return x.LoadedModels };    return nil }
func (x *HealthResponse) GetActiveSessions() uint32     { if x != nil { return x.ActiveSessions };  return 0 }
func (x *HealthResponse) GetWorkerPoolSize() uint32     { if x != nil { return x.WorkerPoolSize };  return 0 }
func (x *HealthResponse) GetWorkerPoolInUse() uint32    { if x != nil { return x.WorkerPoolInUse }; return 0 }
func (x *HealthResponse) GetEngineMode() string         { if x != nil { return x.EngineMode };      return "" }
func (x *HealthResponse) GetEngineTarget() string       { if x != nil { return x.EngineTarget };    return "" }

// ─── ReloadModels ────────────────────────────────────────────────────────────

type ReloadModelsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*ModelEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *ReloadModelsRequest) Reset()         { *x = ReloadModelsRequest{} }
func (x *ReloadModelsRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ReloadModelsRequest) ProtoMessage()    {}
func (x *ReloadModelsRequest) ProtoReflect() protoreflect.Message {
	return messageState(&x.state, x, asrMessageInfos[7])
}
func (x *ReloadModelsRequest) GetEntries() []*ModelEntry { if x != nil { return x.Entries }; return nil }

type ReloadModelsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Loaded []string `protobuf:"bytes,1,rep,name=loaded,proto3" json:"loaded,omitempty"`
	Failed []string `protobuf:"bytes,2,rep,name=failed,proto3" json:"failed,omitempty"`
}

func (x *ReloadModelsResponse) Reset()         { *x = ReloadModelsResponse{} }
func (x *ReloadModelsResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ReloadModelsResponse) ProtoMessage()    {}
func (x *ReloadModelsResponse) ProtoReflect() protoreflect.Message {
	return messageState(&x.state, x, asrMessageInfos[8])
}
func (x *ReloadModelsResponse) GetLoaded() []string { if x != nil { return x.Loaded }; return nil }
func (x *ReloadModelsResponse) GetFailed() []string { if x != nil { return x.Failed }; return nil }

type ModelEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path     string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Language string `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	NThreads int32  `protobuf:"varint,4,opt,name=n_threads,json=nThreads,proto3" json:"n_threads,omitempty"`
	BeamSize int32  `protobuf:"varint,5,opt,name=beam_size,json=beamSize,proto3" json:"beam_size,omitempty"`
}

func (x *ModelEntry) Reset()         { *x = ModelEntry{} }
func (x *ModelEntry) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ModelEntry) ProtoMessage()    {}
func (x *ModelEntry) ProtoReflect() protoreflect.Message {
	return messageState(&x.state, x, asrMessageInfos[9])
}
func (x *ModelEntry) GetId() string       { if x != nil { return x.Id };       return "" }
func (x *ModelEntry) GetPath() string     { if x != nil { return x.Path };     return "" }
func (x *ModelEntry) GetLanguage() string { if x != nil { return x.Language }; return "" }
func (x *ModelEntry) GetNThreads() int32  { if x != nil { return x.NThreads }; return 0 }
func (x *ModelEntry) GetBeamSize() int32  { if x != nil { return x.BeamSize }; return 0 }

// ─── StreamSession (server-streaming, internal/test only) ───────────────────

type StreamChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start *StartSessionRequest `protobuf:"bytes,1,opt,name=start,proto3,oneof" json:"start,omitempty"`
	Audio []byte               `protobuf:"bytes,2,opt,name=audio,proto3,oneof" json:"audio,omitempty"`
	Flush *bool                `protobuf:"varint,3,opt,name=flush,proto3,oneof" json:"flush,omitempty"`
}

func (x *StreamChunk) Reset()         { *x = StreamChunk{} }
func (x *StreamChunk) String() string { return protoimpl.X.MessageStringOf(x) }
func (*StreamChunk) ProtoMessage()    {}
func (x *StreamChunk) ProtoReflect() protoreflect.Message {
	return messageState(&x.state, x, asrMessageInfos[10])
}

type TranscriptEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       string        `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	SegmentId  int32         `protobuf:"varint,2,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	Text       string        `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	StartMs    uint32        `protobuf:"varint,4,opt,name=start_ms,json=startMs,proto3" json:"start_ms,omitempty"`
	EndMs      uint32        `protobuf:"varint,5,opt,name=end_ms,json=endMs,proto3" json:"end_ms,omitempty"`
	Confidence float32       `protobuf:"fixed32,6,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Words      []*WordTiming `protobuf:"bytes,7,rep,name=words,proto3" json:"words,omitempty"`
}

func (x *TranscriptEvent) Reset()         { *x = TranscriptEvent{} }
func (x *TranscriptEvent) String() string { return protoimpl.X.MessageStringOf(x) }
func (*TranscriptEvent) ProtoMessage()    {}
func (x *TranscriptEvent) ProtoReflect() protoreflect.Message {
	return messageState(&x.state, x, asrMessageInfos[11])
}

type WordTiming struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	W       string  `protobuf:"bytes,1,opt,name=w,proto3" json:"w,omitempty"`
	StartMs uint32  `protobuf:"varint,2,opt,name=start_ms,json=startMs,proto3" json:"start_ms,omitempty"`
	EndMs   uint32  `protobuf:"varint,3,opt,name=end_ms,json=endMs,proto3" json:"end_ms,omitempty"`
	P       float32 `protobuf:"fixed32,4,opt,name=p,proto3" json:"p,omitempty"`
}

func (x *WordTiming) Reset()         { *x = WordTiming{} }
func (x *WordTiming) String() string { return protoimpl.X.MessageStringOf(x) }
func (*WordTiming) ProtoMessage()    {}
func (x *WordTiming) ProtoReflect() protoreflect.Message {
	return messageState(&x.state, x, asrMessageInfos[12])
}

// ─── Reflection plumbing ─────────────────────────────────────────────────────
//
// The real protoc-gen-go output embeds a serialised file descriptor here and
// constructs a full reflection table. The gRPC unary client only needs
// MessageInfo entries that can marshal/unmarshal each type via the field tags
// — which protoimpl.X.MessageStateOf does for us.

var asrMessageInfos = func() []*protoimpl.MessageInfo {
	out := make([]*protoimpl.MessageInfo, 13)
	for i := range out {
		out[i] = &protoimpl.MessageInfo{}
	}
	return out
}()

var asrMessageInit sync.Once

func messageState(_ *protoimpl.MessageState, msg any, mi *protoimpl.MessageInfo) protoreflect.Message {
	asrMessageInit.Do(func() {
		types := []reflect.Type{
			reflect.TypeOf((*StartSessionRequest)(nil)),
			reflect.TypeOf((*StartSessionResponse)(nil)),
			reflect.TypeOf((*EndSessionRequest)(nil)),
			reflect.TypeOf((*EndSessionResponse)(nil)),
			reflect.TypeOf((*GetSessionRequest)(nil)),
			reflect.TypeOf((*SessionInfo)(nil)),
			reflect.TypeOf((*HealthResponse)(nil)),
			reflect.TypeOf((*ReloadModelsRequest)(nil)),
			reflect.TypeOf((*ReloadModelsResponse)(nil)),
			reflect.TypeOf((*ModelEntry)(nil)),
			reflect.TypeOf((*StreamChunk)(nil)),
			reflect.TypeOf((*TranscriptEvent)(nil)),
			reflect.TypeOf((*WordTiming)(nil)),
		}
		for i := range asrMessageInfos {
			asrMessageInfos[i].GoReflectType = types[i]
		}
	})
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(reflect.ValueOf(msg).UnsafePointer()))
	if ms.LoadMessageInfo() == nil {
		ms.StoreMessageInfo(mi)
	}
	return ms
}
